name: Flutter Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: 'stable' # or 'dev', 'beta', '2.0.0', etc.

    - name: Get dependencies
      run: flutter pub get

    - name: Build APK
      run: flutter build apk
